// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SatelliteTracker.Infrastructure.Persistence;

#nullable disable

namespace SatelliteTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SatelliteTrackerDbContext))]
    [Migration("20260316015949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SatelliteTracker.Domain.Entities.GroundStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ground_stations", (string)null);
                });

            modelBuilder.Entity("SatelliteTracker.Domain.Entities.Orbit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("ArgumentOfPerigee")
                        .HasColumnType("double precision")
                        .HasColumnName("argument_of_perigee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Eccentricity")
                        .HasColumnType("double precision")
                        .HasColumnName("eccentricity");

                    b.Property<DateTime>("Epoch")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("epoch");

                    b.Property<double>("Inclination")
                        .HasColumnType("double precision")
                        .HasColumnName("inclination");

                    b.Property<double>("MeanAnomaly")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_anomaly");

                    b.Property<double>("MeanMotion")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_motion");

                    b.Property<double>("RightAscension")
                        .HasColumnType("double precision")
                        .HasColumnName("raan");

                    b.Property<Guid>("SatelliteId")
                        .HasColumnType("uuid")
                        .HasColumnName("satellite_id");

                    b.Property<string>("TleLine1")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("tle_line1");

                    b.Property<string>("TleLine2")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("tle_line2");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteId");

                    b.ToTable("orbits", (string)null);
                });

            modelBuilder.Entity("SatelliteTracker.Domain.Entities.Satellite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InternationalDesignator")
                        .HasColumnType("text")
                        .HasColumnName("international_designator");

                    b.Property<DateTime?>("LaunchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("launch_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NoradId")
                        .HasColumnType("integer")
                        .HasColumnName("norad_id");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NoradId")
                        .IsUnique();

                    b.ToTable("satellites", (string)null);
                });

            modelBuilder.Entity("SatelliteTracker.Domain.Entities.Telemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_level");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("SatelliteId")
                        .HasColumnType("uuid")
                        .HasColumnName("satellite_id");

                    b.Property<double?>("SignalStrength")
                        .HasColumnType("double precision")
                        .HasColumnName("signal_strength");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Velocity")
                        .HasColumnType("double precision")
                        .HasColumnName("velocity");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("telemetry", (string)null);
                });

            modelBuilder.Entity("SatelliteTracker.Domain.Entities.Orbit", b =>
                {
                    b.HasOne("SatelliteTracker.Domain.Entities.Satellite", null)
                        .WithMany()
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SatelliteTracker.Domain.Entities.Telemetry", b =>
                {
                    b.HasOne("SatelliteTracker.Domain.Entities.Satellite", null)
                        .WithMany()
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
